name: dataprofile_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - scikit-learn>=1.0.0,<1.4.0
  - numpy>=1.20.0
  - pandas>=2.0.0
  - tabulate>=0.8.0
  - click>=8.0.0
  - tqdm>=4.65.0
  - colorama>=0.4.0
  - loguru>=0.7.0
  # Dev dependencies
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - flake8>=6.0.0
  - flake8-docstrings>=1.7.0
  - flake8-bandit>=4.1.1
  - mypy>=1.0.0
  - pip
  - pip:
    - -e .  # Install the current package in editable mode
